apiVersion: v1
kind: Pod
metadata:
  name: tetrisapp
  labels:
    app: tetrisapp
spec:
  containers:
    - name: tetrisapp
      image: darrs08/tetrisapp:tagVersion
      ports:
        - containerPort: 8080
